# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 18 Aug 2017 17:12:45 +0000
*               @ALL          0
*               @user         8
